export const SET_USER = "SET_USER";
export const LOG_OUT = "LOG_OUT";
export const SET_JWT = "SET_JWT";

export const ADD_USER_UPLOAD = "ADD_USER_UPLOAD";
export const SET_ALL_USER_UPLOADS = "SET_ALL_USER_UPLOADS";
export const ADD_FINISHED_PHOTO = "ADD_FINISHED_PHOTO";
export const SET_ALL_FINISHED_PHOTOS = "SET_ALL_FINISHED_PHOTOS";
